FROM yoanlin/opencv-python3

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PYTHONUNBUFFERED=1

WORKDIR /api/

COPY requirements.txt ./

# RUN apt update && \
#     apt install libgtk2.0-dev -y && apt clean

#RUN apt-get update & apt-get install python3-pip -y

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt && \
    rm requirements.txt

COPY app/ .

EXPOSE 5000

ENTRYPOINT ["python","wsgi.py"]